#memory
1, 0, SPECIAL, mem_read
1, 1, SPECIAL, mem_write
#control
2, 0, CATEGORY, COND_BR
2, 1, CATEGORY, UNCOND_BR
2, 2, OPCODE, LEAVE
2, 3, OPCODE, RET_NEAR
2, 4, OPCODE, CALL_NEAR
#scalar
3, 0, CATEGORY, LOGICAL
3, 1, CATEGORY, DATAXFER
3, 2, CATEGORY, BINARY
3, 3, CATEGORY, FLAGOP
3, 4, CATEGORY, BITBYTE
3, 5, CATEGORY, SHIFT
#fp scalaar
4, 0, CATEGORY, X87_ALU
4, 1, CATEGORY, FCMOV
4, 2, CATEGORY, LOGICAL_FP
#nop
5, 0, CATEGORY, WIDENOP
5, 1, CATEGORY, NOP
#register
6, 0, SPECIAL, reg_transfer
#vector
7, 0, CATEGORY, SSE
7, 1, CATEGORY, AVX
7, 2, CATEGORY, AVX2
7, 3, CATEGORY, MMX
